# frontend/dockerfile
FROM node:22-alpine

# Install pnpm
RUN npm i -g pnpm@10.17.1

WORKDIR /usr/src/app

# Copy lockfiles first for better caching
COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

# Copy rest of the frontend code
COPY . .

EXPOSE 5173

# Run vite in dev mode, with --host so it's accessible outside container
CMD ["pnpm", "dev", "--host"]